import json
import sys
from pathlib import Path

from api2agent.diagnostics import diagnose_capability
from api2agent.generators.mcp import render_mcp_server
from api2agent.generators.readme import render_readme
from api2agent.generators.runner import render_runner
from api2agent.generators.smoke_test import render_manual_write_test, render_smoke_test
from api2agent.generators.tools import to_openai_tools
from api2agent.ir.models import Capability


def generate_package(capability: Capability, output_dir: Path, force: bool = False) -> Path:
    if output_dir.exists() and any(output_dir.iterdir()) and not force:
        raise FileExistsError(
            f"Output directory is not empty: {output_dir}. Use --force to overwrite generated files."
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    examples_dir = output_dir / "examples"
    examples_dir.mkdir(exist_ok=True)
    diagnostics = diagnose_capability(capability)

    _write_json(output_dir / "capability.json", capability.model_dump(mode="json", by_alias=True))
    _write_json(output_dir / "tools.json", to_openai_tools(capability))
    _write_json(output_dir / "diagnostics.json", diagnostics)
    _write_text(output_dir / "auth.env.example", _render_auth_env(capability))
    _write_text(output_dir / "README.md", render_readme(capability, diagnostics=diagnostics))
    _write_text(output_dir / "runner.py", render_runner(capability))
    _write_text(output_dir / "smoke_test.py", render_smoke_test(capability))
    _write_text(output_dir / "manual_write_test.py", render_manual_write_test(capability))
    _write_text(output_dir / "mcp_server.py", render_mcp_server(capability))
    _write_text(examples_dir / "openai_agent.py", _render_openai_placeholder(capability))
    _write_text(examples_dir / "claude_desktop_config.json", _render_claude_config(capability, output_dir))

    return output_dir


def _write_json(path: Path, data: object) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def _render_auth_env(capability: Capability) -> str:
    env_names = []
    for auth in [capability.auth] + [tool.auth for tool in capability.tools if tool.auth is not None]:
        for env in _auth_env_names(auth):
            if env not in env_names:
                env_names.append(env)

    if not env_names:
        return "# This API does not require auth based on the parsed spec.\n"
    lines = ["# Fill these before running generated tools that require auth."]
    lines.extend(f"{name}=" for name in env_names)
    return "\n".join(lines) + "\n"


def _auth_env_names(auth) -> list[str]:
    credentials = auth.credentials or []
    if not credentials:
        credentials = [auth.model_dump(mode="json", by_alias=True)]

    envs: list[str] = []
    for credential in credentials:
        if credential.get("type") in {"api_key", "bearer"} and credential.get("env"):
            envs.append(str(credential["env"]))
    return envs


def _render_openai_placeholder(capability: Capability) -> str:
    template = '''"""OpenAI tool-calling example for __CAPABILITY_NAME__.

This file is generated as a starting point. It does not add OpenAI as a
runtime dependency for the generated package; install the OpenAI SDK before
running `main()`.
"""

import json
import os
import sys
from pathlib import Path


PACKAGE_DIR = Path(__file__).resolve().parents[1]
if str(PACKAGE_DIR) not in sys.path:
    sys.path.insert(0, str(PACKAGE_DIR))

from runner import execute_tool


def load_tools() -> list[dict]:
    """Load generated tools and adapt them for the Responses API."""
    return [_responses_tool(tool) for tool in load_generated_tools()]


def load_generated_tools() -> list[dict]:
    """Load the raw OpenAI-compatible tool definitions generated by API2Agent."""
    return json.loads((PACKAGE_DIR / "tools.json").read_text(encoding="utf-8"))


def dispatch_tool_call(tool_call) -> dict:
    """Execute one OpenAI function_call item through the generated runner."""
    name = _tool_call_field(tool_call, "name")
    raw_arguments = _tool_call_field(tool_call, "arguments") or "{}"
    try:
        arguments = json.loads(raw_arguments)
    except json.JSONDecodeError as exc:
        return {"ok": False, "error": {"type": "invalid_tool_arguments", "message": str(exc)}}
    if not isinstance(arguments, dict):
        return {"ok": False, "error": {"type": "invalid_tool_arguments", "message": "tool arguments must be a JSON object"}}
    return execute_tool(name, arguments)


def main() -> None:
    """Run a minimal Responses API tool-calling loop."""
    try:
        from openai import OpenAI
    except ImportError as exc:
        raise SystemExit("Install the OpenAI SDK first: python -m pip install openai") from exc

    prompt = os.getenv("API2AGENT_OPENAI_PROMPT", "Use the available API tool once with safe example inputs.")
    model = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")
    input_items = [{"role": "user", "content": prompt}]
    client = OpenAI()
    response = client.responses.create(
        model=model,
        input=input_items,
        tools=load_tools(),
    )

    input_items += response.output
    tool_outputs = []
    for item in response.output:
        if _tool_call_field(item, "type") != "function_call":
            continue
        result = dispatch_tool_call(item)
        tool_outputs.append(
            {
                "type": "function_call_output",
                "call_id": _tool_call_field(item, "call_id"),
                "output": json.dumps(result, ensure_ascii=False),
            }
        )

    if not tool_outputs:
        print(response.output_text)
        return

    input_items.extend(tool_outputs)
    final = client.responses.create(
        model=model,
        input=input_items,
        tools=load_tools(),
    )
    print(final.output_text)


def _responses_tool(tool: dict) -> dict:
    if tool.get("type") == "function" and "function" in tool:
        function = tool["function"]
        return {
            "type": "function",
            "name": function["name"],
            "description": function.get("description") or function["name"],
            "parameters": function.get("parameters") or {"type": "object", "properties": {}},
        }
    return tool


def _tool_call_field(tool_call, field: str):
    if isinstance(tool_call, dict):
        return tool_call.get(field)
    return getattr(tool_call, field, None)


if __name__ == "__main__":
    main()
'''
    return template.replace("__CAPABILITY_NAME__", capability.name)


def _render_claude_config(capability: Capability, output_dir: Path) -> str:
    config = {
        "mcpServers": {
            capability.name: {
                "command": sys.executable,
                "args": [str((output_dir / "mcp_server.py").resolve())],
            }
        }
    }
    return json.dumps(config, indent=2) + "\n"
