from api2agent.ir.models import Capability


def render_readme(capability: Capability) -> str:
    auth_note = "No auth detected."
    if capability.auth.type != "none" and capability.auth.env:
        auth_note = f"Copy auth.env.example to .env and set {capability.auth.env}."

    tools = "\n".join(_format_tool(tool) for tool in capability.tools)
    first_tool = capability.tools[0] if capability.tools else None
    example_tool = first_tool.name if first_tool else ""
    example_params = _example_params(first_tool) if first_tool else {}

    return f"""# {capability.name}

Generated by API2Agent.

## Auth

{auth_note}

## Tools

{tools}

## Smoke Test

```bash
python smoke_test.py
```

The smoke test exits with a non-zero code when the generated call fails.

Common errors:

- `missing_auth`: copy `auth.env.example` to `.env` and fill the required env var.
- `missing_parameters`: provide the required parameters shown in the error.
- `http_status`: the API returned a non-2xx response. Check auth, params, and endpoint availability.

## Runner

```python
from runner import execute_tool

result = execute_tool("{example_tool}", {example_params!r})
print(result)
```

## Proxy Mode

Direct local execution is the default. To route generated calls through API2Agent Proxy for usage tracking, latency measurement, cost estimation, and quota control, start the proxy:

```bash
api2agent proxy --db api2agent-usage.sqlite --port 8765 --quota 1000
```

Then run the generated tools with:

```bash
API2AGENT_PROXY_URL=http://127.0.0.1:8765
API2AGENT_PROJECT_ID=local
API2AGENT_PROVIDER_ID={capability.name}
```

View usage:

```bash
api2agent usage --db api2agent-usage.sqlite --project-id local
```
"""


def _format_tool(tool) -> str:
    lines = [f"- `{tool.name}`: {tool.method} {tool.path} [{tool.safety}]"]
    by_location = {"path": [], "query": [], "header": []}
    for parameter in tool.parameters:
        by_location[parameter.location].append(parameter)

    for location, parameters in by_location.items():
        if parameters:
            lines.append("  - " + location + ": " + ", ".join(_format_parameter(parameter) for parameter in parameters))

    if tool.request_body is not None:
        required = " required" if tool.request_body.required else ""
        lines.append(f"  - body: {_format_schema(tool.request_body.schema_)}{required}")

    return "\n".join(lines)


def _format_parameter(parameter) -> str:
    required = " required" if parameter.required else ""
    return f"{parameter.name} {_format_schema(parameter.schema_)}{required}"


def _format_schema(schema: dict) -> str:
    schema_type = schema.get("type")
    if schema_type == "object":
        properties = schema.get("properties") or {}
        if not properties:
            return "object"
        fields = ", ".join(f"{name}:{_format_schema(value)}" for name, value in properties.items())
        return f"object {{{fields}}}"
    if schema_type == "array":
        return f"array[{_format_schema(schema.get('items') or {})}]"
    if "oneOf" in schema:
        return "oneOf[" + " | ".join(_format_schema(item) for item in schema["oneOf"]) + "]"
    if "anyOf" in schema:
        return "anyOf[" + " | ".join(_format_schema(item) for item in schema["anyOf"]) + "]"

    label = str(schema_type or "unknown")
    if "default" in schema:
        label += f" default={schema['default']}"
    return label


def _example_params(tool) -> dict:
    if tool is None:
        return {}

    params = {}
    for parameter in tool.parameters:
        if parameter.required or "default" in parameter.schema_:
            params[parameter.name] = parameter.schema_.get("default", _example_value(parameter.schema_))

    if tool.request_body is not None and tool.request_body.required:
        params["body"] = _example_value(tool.request_body.schema_)

    return params


def _example_value(schema: dict):
    schema_type = schema.get("type")
    if "default" in schema:
        return schema["default"]
    if schema_type == "object":
        return {
            name: _example_value(value)
            for name, value in (schema.get("properties") or {}).items()
        }
    if schema_type == "array":
        return [_example_value(schema.get("items") or {})]
    if schema_type == "integer":
        return 1
    if schema_type == "number":
        return 1
    if schema_type == "boolean":
        return True
    return "example"
