import json
from collections import Counter

from api2agent.generators.examples import example_for_parameter, example_for_request_body, example_value
from api2agent.ir.models import Capability
from api2agent.response_docs import format_response_summaries
from api2agent.schema_shaping import SchemaDirection, summarize_schema


def render_readme(capability: Capability, diagnostics: dict | None = None) -> str:
    auth_note = _auth_note(capability)
    region_note = "No provider region metadata configured."
    if capability.provider_region:
        region_note = f"Provider region: `{capability.provider_region}`."
    server_section = _server_section(capability)
    package_overview = _package_overview(capability, diagnostics)

    tools = "\n".join(_format_tool(tool) for tool in capability.tools)
    first_tool = capability.tools[0] if capability.tools else None
    example_tool = first_tool.name if first_tool else ""
    example_params = _example_params(first_tool) if first_tool else {}
    example_params_json = json.dumps(example_params)
    diagnostics_section = _diagnostics_section(diagnostics)

    return f"""# {capability.name}

Generated by API2Agent.

{diagnostics_section}

{package_overview}

## Auth

{auth_note}

## Provider Region

{region_note}

Set `API2AGENT_PROVIDER_REGION` at runtime to override the generated provider-region intent for proxy calls.

## Base URL Override

Generated tools use the OpenAPI/curl base URL by default. For local, staging, or region-specific endpoints, override it at runtime:

{server_section}

```bash
API2AGENT_BASE_URL=http://127.0.0.1:9001
```

For one generated tool only, set:

```bash
API2AGENT_TOOL_BASE_URL_{_tool_base_url_suffix(example_tool)}=http://127.0.0.1:9002
```

## Tools

{tools}

## Smoke Test

```bash
python smoke_test.py
```

The smoke test exits with a non-zero code when the generated call fails.
It only uses read-only tools when one is available.

For large packages or targeted read checks, run one generated tool explicitly:

```bash
api2agent test . --tool {example_tool} --params '{example_params_json}'
```

For write/delete tools, use the explicit manual path:

```bash
api2agent test . --allow-write
```

This runs `manual_write_test.py` with `API2AGENT_ALLOW_WRITE_TEST=1`.

Common errors:

- `missing_auth`: copy `auth.env.example` to `.env` and fill the required env var.
- `missing_parameters`: provide the required parameters shown in the error.
- `http_status`: the API returned a non-2xx response. Check auth, params, and endpoint availability.

## Runner

```python
from runner import execute_tool

result = execute_tool("{example_tool}", {example_params!r})
print(result)
```

## Proxy Mode

Direct local execution is the default. To route generated calls through API2Agent Proxy for usage tracking, latency measurement, cost estimation, and quota control, start the proxy:

```bash
api2agent proxy --db api2agent-usage.sqlite --port 8765 --quota 1000
```

Then run the generated tools with:

```bash
API2AGENT_PROXY_URL=http://127.0.0.1:8765
API2AGENT_PROJECT_ID=local
API2AGENT_PROVIDER_ID={capability.name}
API2AGENT_PROVIDER_REGION={capability.provider_region or ""}
```

View usage:

```bash
api2agent usage --db api2agent-usage.sqlite --project-id local
```
"""


def _diagnostics_section(diagnostics: dict | None) -> str:
    if not diagnostics:
        return ""
    summary = diagnostics.get("summary") or {}
    status = diagnostics.get("status", "unknown")
    score = diagnostics.get("score", "unknown")
    lines = [
        "## Diagnostics",
        "",
        f"Status: `{status}`. Score: `{score}`.",
        "",
        "Findings: "
        + f"errors={summary.get('errors', 0)}, "
        + f"warnings={summary.get('warnings', 0)}, "
        + f"info={summary.get('info', 0)}.",
        "",
        "Run `api2agent diagnose .` for details.",
        "",
    ]
    return "\n".join(lines)


def _package_overview(capability: Capability, diagnostics: dict | None) -> str:
    tools = capability.tools
    safety_counts = Counter(str(tool.safety) for tool in tools)
    lines = [
        "## Package Overview",
        "",
        f"- Tools: {len(tools)}",
    ]
    if safety_counts:
        ordered = [key for key in ["read", "write", "delete", "unknown"] if key in safety_counts]
        ordered.extend(sorted(key for key in safety_counts if key not in ordered))
        lines.append("- Safety: " + ", ".join(f"{key}={safety_counts[key]}" for key in ordered))
    if diagnostics:
        status = diagnostics.get("status", "unknown")
        score = diagnostics.get("score", "unknown")
        lines.append(f"- Diagnostics: {status} score={score}")
        caveats = _top_finding_counts(diagnostics.get("findings") or [])
        if caveats:
            lines.append("- Key caveats: " + ", ".join(f"{finding_id}({count})" for finding_id, count in caveats))
    lines.append("")
    return "\n".join(lines)


def _top_finding_counts(findings: list[dict], *, limit: int = 5) -> list[tuple[str, int]]:
    severity_rank = {"error": 0, "warning": 1, "info": 2}
    counts: Counter[str] = Counter(str(finding.get("id") or "unknown") for finding in findings)
    severities: dict[str, int] = {}
    for finding in findings:
        finding_id = str(finding.get("id") or "unknown")
        severity = str(finding.get("severity") or "info")
        rank = severity_rank.get(severity, len(severity_rank))
        severities[finding_id] = min(severities.get(finding_id, rank), rank)
    ranked = sorted(counts.items(), key=lambda item: (severities.get(item[0], 99), -item[1], item[0]))
    return ranked[:limit]


def _format_tool(tool) -> str:
    server = f" [server: {tool.server_source}]" if tool.server_source in {"path", "operation"} else ""
    lines = [f"- `{tool.name}`: {tool.method} {tool.path} [{tool.safety}] [{_format_auth(tool.auth)}]{server}"]
    by_location = {"path": [], "query": [], "header": []}
    for parameter in tool.parameters:
        by_location[parameter.location].append(parameter)

    for location, parameters in by_location.items():
        if parameters:
            lines.append("  - " + location + ": " + ", ".join(_format_parameter(parameter) for parameter in parameters))

    if tool.request_body is not None:
        required = " required" if tool.request_body.required else ""
        example = ""
        if tool.request_body.example is not None or tool.request_body.examples or _schema_has_example(tool.request_body.schema_):
            example = f" example={example_for_request_body(tool.request_body)}"
        lines.append(f"  - body: {_format_schema(tool.request_body.schema_, direction='request')}{required}{example}")

    if tool.responses:
        lines.append("  - responses:")
        for summary in format_response_summaries(tool.responses):
            lines.append(f"    - {summary}")

    return "\n".join(lines)


def _auth_note(capability: Capability) -> str:
    env_names = []
    for auth in [capability.auth] + [tool.auth for tool in capability.tools if tool.auth is not None]:
        for env in _auth_env_names(auth):
            if env not in env_names:
                env_names.append(env)

    if not env_names:
        return "No auth detected."
    return "Copy auth.env.example to .env and set " + ", ".join(f"`{name}`" for name in env_names) + "."


def _server_section(capability: Capability) -> str:
    servers = capability.servers or []
    if not servers:
        return "No OpenAPI servers were detected. Set `API2AGENT_BASE_URL` before execution."

    lines = ["Known OpenAPI servers:"]
    for server in servers:
        hints = f" hints={','.join(server.profile_hints)}" if server.profile_hints else ""
        relative = " relative" if server.is_relative else ""
        description = f" - {server.description}" if server.description else ""
        lines.append(
            f"- `{server.resolved_url}` ({server.source}{relative}{hints}){description}"
        )
    if any(server.is_relative for server in servers):
        lines.append("")
        lines.append("Relative server URLs require `API2AGENT_BASE_URL` to provide the real provider origin.")
    return "\n".join(lines)


def _format_auth(auth) -> str:
    if auth is None:
        return "auth: inherit"
    credentials = auth.credentials or []
    if len(credentials) > 1:
        return "auth: combined " + " + ".join(_format_auth_credential(credential) for credential in credentials)
    return "auth: " + _format_auth_credential(auth.model_dump(mode="json", by_alias=True))


def _format_auth_credential(auth: dict) -> str:
    auth_type = auth.get("type") or "none"
    if auth_type == "none":
        return "none"
    location = auth.get("location")
    name = auth.get("name") or auth.get("header")
    env = auth.get("env")
    if location and name and env:
        return f"{auth_type} via {location}:{name} env={env}"
    if env:
        return f"{auth_type} env={env}"
    return auth_type


def _auth_env_names(auth) -> list[str]:
    credentials = auth.credentials or []
    if not credentials:
        credentials = [auth.model_dump(mode="json", by_alias=True)]

    envs: list[str] = []
    for credential in credentials:
        if credential.get("type") in {"api_key", "bearer"} and credential.get("env"):
            envs.append(str(credential["env"]))
    return envs


def _tool_base_url_suffix(tool_name: str) -> str:
    suffix = "".join(
        char.upper() if char.isalnum() else "_"
        for char in str(tool_name or "TOOL")
    ).strip("_")
    return suffix or "TOOL"


def _format_parameter(parameter) -> str:
    required = " required" if parameter.required else ""
    example = ""
    if parameter.example is not None or parameter.examples or _schema_has_example(parameter.schema_):
        example = f" example={example_for_parameter(parameter)}"
    return f"{parameter.name} {_format_schema(parameter.schema_)}{required}{example}"


def _format_schema(schema: dict, *, direction: SchemaDirection = "neutral") -> str:
    return summarize_schema(schema, direction=direction)


def _example_params(tool) -> dict:
    if tool is None:
        return {}

    params = {}
    for parameter in tool.parameters:
        if parameter.required or _parameter_has_example(parameter):
            params[parameter.name] = example_for_parameter(parameter)

    if tool.request_body is not None and tool.request_body.required:
        params["body"] = example_for_request_body(tool.request_body)

    return params


def _example_value(schema: dict):
    return example_value(schema)


def _schema_has_example(schema: dict) -> bool:
    return any(key in schema for key in ["default", "example", "examples", "enum"])


def _parameter_has_example(parameter) -> bool:
    return parameter.example is not None or bool(parameter.examples) or _schema_has_example(parameter.schema_)
